language: node_js
node_js:
- 13.2
cache: npm
script: 
 - travis_wait npm run test
deploy:
  provider: s3
  cleanup: true
  skip_cleanup: true
  access_key_id: AKIAZIUCQ6FCAA452VX2
  secret_access_key: 
    secure: "VweSWXpse4+oVDgw9TdoEsMPo11/VE7bZUi7QkNjJ22n/Oxd6wyzNh49Wips3gKTP9KSqp4JS3X8/Dxd5lGEZCZqkN1il9U08950xL0LNDT7e7QMKg+2XdwA5cIZvFrFtoJhdZGxG413nGoeAOxjDBRFDXgfN1CWrwZj+ZmaTtFcy5rLI4pvw8eexcUeV6eE0OxRdX1SnCWTkJL2UosNKy9NeE7g9f/x+1WZsys6VyZRlcmsVbGkCD4wULC1lyDFFn/kVFkbWP4xQKcDu9Af3U42X/cBfiUJTIzUVcX2SYLjLOu304TzdfTiWD/1AyRh1eB67i29/CbuXMxRqPllzzD86Yteszw0UmJ+lNLnH8gDbsFZPAtOhUOgnfHJH6Q1Nm2NPZblj8hJxf7MzoJEnss+XOvNy01I5blF4ifQYR7zlY7yr5WTCHZ5hH6B1y2Iw0GgPMg8waOGwljpGbG9GW4JlicXa3+c2VN9tItlucOL+08S3MWUzfUYTd6eqATw8neZUWUPOTUMPE8DbbkSBIa4eWRLT/Zjn5XBLN1keNuB0UAoJKXqDueL69kvBq9jNjwu/oAXW0/LlBtjf965sFbr2LJABrJObO0GvXCSSZ9cB0BEQq+QTcDbtw8OLYb7B6VuVF356rXrDAGGlxyfq1Yxq38GCCD/eHK7a/ZgJ84="
  bucket: alpheios-misc-dev
  region: us-east-2
  local_dir: public
  upload_dir: selenium-tests
  acl: public_read
  cache_control: no-cache
  on:
    repo: alpheios-project/selenium-tests
    branch: travis
